const productCharacteristics = {
  brand: 'Производитель',
  model: 'Модель',
  memoryDb: 'Объем видеопамяти',
  memoryType: 'Тип видеопамяти',
  country: 'Страна',
  cores: 'Количество ядер',
  clockFrequency: 'Частота',
  turboFrequency: 'Частота в турбо режиме',
  heatDissipation: 'Рассеиваемая мощность',
  chipset: 'Чипсет',
  socket: 'Сокет',
  timings: 'Тайминги',
  ramDb: 'Объем оперативной памяти',
  frequency: 'Частота',
  height: 'Высота',
  width: 'Ширина',
  material: 'Материал',
  depth: 'Глубина',
  speed: 'Скорость',
  coolerPower: 'Сила кулера',
  voltage: 'Вольтаж',
  battery: 'Батарея',
  capacity: 'Объем хранилища',
} as const;

export default productCharacteristics;
